/* ================= DATA (per-language) ================= */
const PROGRAMS = [
 {code:"CS-PRI",seed:"centre-souifi-prim",
  en:{title:"Primary · CP → CM2",meta:"EVENING SESSIONS",tag:"Solid foundations for a big life.",desc:"Homework help, mathematics, French and scientific discovery — small groups, gentle methodology, and homework finished and understood before home.",days:"Set with the teacher",length:"All school year",level:"CP – CM2",fee:"250 MAD / month",teacher:"Nadia Tazi & team"},
  fr:{title:"Primaire · CP → CM2",meta:"SÉANCES DU SOIR",tag:"Des bases solides pour une grande vie !",desc:"Aide aux devoirs, mathématiques, français et éveil scientifique — petits groupes, méthodologie en douceur, et des devoirs terminés et compris avant la maison.",days:"À définir avec le prof",length:"Toute l'année scolaire",level:"CP – CM2",fee:"250 MAD / mois",teacher:"Nadia Tazi & l'équipe"},
  ar:{title:"الابتدائي · من الأولى إلى السادسة",meta:"حصص مسائية",tag:"أساس متين لحياة كبيرة.",desc:"مساعدة في الواجبات والرياضيات والفرنسية والاكتشاف العلمي — مجموعات صغيرة ومنهجية لطيفة، وواجبات منجزة ومفهومة قبل العودة إلى البيت.",days:"تُحدد مع الأستاذ",length:"السنة الدراسية كاملة",level:"الابتدائي · 1 – 6",fee:"250 درهم / شهريًا",teacher:"نادية التازي والفريق"}},
 {code:"CS-COL",seed:"centre-souifi-col",
  en:{title:"Collège · 1st → 3rd year",meta:"EVENING SESSIONS",tag:"Progress today, succeed tomorrow.",desc:"Mathematics, physical sciences, SVT, French and English — plus methodology & organisation and steady preparation for the 3rd-year regional exam.",days:"Set with the teacher",length:"All school year",level:"1ère – 3ème AC",fee:"300 MAD / month",teacher:"Omar Chraibi"},
  fr:{title:"Collège · De la 1ère à la 3ème",meta:"SÉANCES DU SOIR",tag:"Progresser aujourd'hui, réussir demain !",desc:"Mathématiques, sciences physiques, SVT, français et anglais — plus méthodologie & organisation et une préparation solide à l'examen régional de la 3ème année.",days:"À définir avec le prof",length:"Toute l'année scolaire",level:"1ère – 3ème AC",fee:"300 MAD / mois",teacher:"Omar Chraibi"},
  ar:{title:"الإعدادي · من الأولى إلى الثالثة",meta:"حصص مسائية",tag:"تقدّم اليوم، انجح غدًا.",desc:"الرياضيات والعلوم الفيزيائية وعلوم الحياة والأرض والفرنسية والإنكليزية — مع المنهجية والتنظيم وتحضير متين للامتحان الجهوي للثالثة إعدادي.",days:"تُحدد مع الأستاذ",length:"السنة الدراسية كاملة",level:"الأولى – الثالثة إعدادي",fee:"300 درهم / شهريًا",teacher:"عمر الشرايبي"}},
 {code:"CS-LYC",seed:"centre-souifi-lyc",
  en:{title:"Lycée · TC → 2BAC",meta:"EVENING SESSIONS",tag:"Ambition today, achievement tomorrow.",desc:"Maths, Physics-Chemistry, SVT, Economics & Management, Philosophy, French and English — with preparation for the 1BAC regional and 2BAC national exams, plus orientation and confidence.",days:"Set with the teacher",length:"All school year",level:"TC – 2BAC",fee:"350 MAD / month",teacher:"Salma Benkirane"},
  fr:{title:"Lycée · Seconde → Terminale",meta:"SÉANCES DU SOIR",tag:"Ambition aujourd'hui, réussite demain !",desc:"Maths, Physique-Chimie, SVT, Économie & Gestion, Philosophie, français et anglais — avec préparation au régional de 1BAC et au national de 2BAC, orientation et confiance.",days:"À définir avec le prof",length:"Toute l'année scolaire",level:"TC – 2BAC",fee:"350 MAD / mois",teacher:"Salma Benkirane"},
  ar:{title:"التأهيلي · الجذع – الثانية باك",meta:"حصص مسائية",tag:"طموح اليوم، نجاح الغد.",desc:"الرياضيات والفيزياء-الكيمياء وعلوم الحياة والأرض والاقتصاد والتدبير والفلسفة واللغات — مع التحضير للجهوي الأولى باك والوطني الثانية باك، والتوجيه والثقة.",days:"تُحدد مع الأستاذ",length:"السنة الدراسية كاملة",level:"الجذع المشترك – 2باك",fee:"350 درهم / شهريًا",teacher:"سلمى بنكيران"}},
 {code:"CS-LNG",seed:"centre-souifi-lang",
  en:{title:"Languages · FR · EN · AR",meta:"EVENING SESSIONS",tag:"Speak a language, open the world.",desc:"French, English and Arabic in small level-matched groups — conversation first, grammar quietly comes along.",days:"Set with the teacher",length:"All school year",level:"All levels",fee:"250 MAD / month",teacher:"Nadia Tazi"},
  fr:{title:"Langues · Français · Anglais · Arabe",meta:"SÉANCES DU SOIR",tag:"Parler une langue, ouvrir le monde.",desc:"Français, anglais et arabe en petits groupes par niveau — la conversation d'abord, la grammaire suit en silence.",days:"À définir avec le prof",length:"Toute l'année scolaire",level:"Tous niveaux",fee:"250 MAD / mois",teacher:"Nadia Tazi"},
  ar:{title:"اللغات · الفرنسية · الإنكليزية · العربية",meta:"حصص مسائية",tag:"أتقن لغة، افتح العالم.",desc:"الفرنسية والإنكليزية والعربية في مجموعات صغيرة حسب المستوى — المحادثة أولًا، والقواعد تأتي خلسة.",days:"تُحدد مع الأستاذ",length:"السنة الدراسية كاملة",level:"كل المستويات",fee:"250 درهم / شهريًا",teacher:"نادية التازي"}},
 {code:"CS-ETD",seed:"centre-souifi-etude",
  en:{title:"Supervised Study",meta:"EVERY EVENING",tag:"Homework done — and understood.",desc:"A quiet room, a teacher walking between the desks, and progress tracked for every pupil. Open to all levels.",days:"Every evening",length:"All school year",level:"All levels",fee:"200 MAD / month",teacher:"Rotating teachers"},
  fr:{title:"Étude surveillée",meta:"TOUS LES SOIRS",tag:"Les devoirs faits — et compris.",desc:"Une salle calme, un enseignant qui circule entre les tables, et un suivi des progrès pour chaque élève. Ouvert à tous les niveaux.",days:"Tous les soirs",length:"Toute l'année scolaire",level:"Tous niveaux",fee:"200 MAD / mois",teacher:"Enseignants en rotation"},
  ar:{title:"الدراسة الموجّهة",meta:"كل مساء",tag:"الواجبات منجزة — ومفهومة.",desc:"قاعة هادئة، وأستاذ يتنقل بين المكاتب، وتتبع لتقدم كل تلميذ. مفتوحة لجميع المستويات.",days:"كل مساء",length:"السنة الدراسية كاملة",level:"كل المستويات",fee:"200 درهم / شهريًا",teacher:"أساتذة بالتناوب"}},
 {code:"CS-EXM",seed:"centre-souifi-exam",
  en:{title:"Exam Prep · Regional & National",meta:"BEFORE EACH EXAM",tag:"Six weeks before the exam. Together.",desc:"Before every official exam — 3AC regional, 1BAC regional, 2BAC national — a six-week sprint: past papers, mock exams under real conditions, and a revision plan your child actually follows.",days:"6 weeks before the exam",length:"6-week sprints",level:"3AC · 1BAC · 2BAC",fee:"400 MAD / sprint",teacher:"The full team"},
  fr:{title:"Préparation aux examens · Régional & National",meta:"AVANT CHAQUE EXAMEN",tag:"Six semaines avant l'examen. Ensemble.",desc:"Avant chaque examen officiel — régional 3AC, régional 1BAC, national 2BAC — un sprint de six semaines : annales, examens blancs en conditions réelles, et un plan de révision que votre enfant suit vraiment.",days:"6 semaines avant l'examen",length:"Sprints de 6 semaines",level:"3AC · 1BAC · 2BAC",fee:"400 MAD / sprint",teacher:"Toute l'équipe"},
  ar:{title:"التحضير للامتحانات · الجهوي والوطني",meta:"قبل كل امتحان",tag:"ستة أسابيع قبل الامتحان. معًا.",desc:"قبل كل امتحان رسمي — الجهوي الثالثة إعدادي، الجهوي الأولى باك، الوطني الثانية باك — ستة أسابيع مكثفة: امتحانات سابقة، اختبارات تجريبية بشروط حقيقية، وخطة مراجعة يلتزم بها ابنك فعلًا.",days:"6 أسابيع قبل الامتحان",length:"6 أسابيع مكثفة",level:"3إعدادي · 1باك · 2باك",fee:"400 درهم / أسابيع",teacher:"الفريق كاملًا"}}
];
const LI = {en:0,fr:1,ar:2};
const QUOTES = [
 {en:{q:"Education is the passport to the future, for tomorrow belongs to those who prepare for it today.",n:"Malcolm X",m:"On preparing today"},
  fr:{q:"L'éducation est le passeport vers l'avenir, car demain appartient à ceux qui s'y préparent aujourd'hui.",n:"Malcolm X",m:"Sur la préparation d'aujourd'hui"},
  ar:{q:"التعليم جواز سفر إلى المستقبل، فالغد ملكٌ لمن يستعدّ له اليوم.",n:"مالكوم إكس",m:"عن الاستعداد اليوم"}},
 {en:{q:"It always seems impossible until it is done.",n:"Nelson Mandela",m:"On finishing hard work"},
  fr:{q:"Cela semble toujours impossible, jusqu'à ce que ce soit fait.",n:"Nelson Mandela",m:"Sur le travail difficile"},
  ar:{q:"يبدو الأمر مستحيلًا دائمًا، إلى أن يتمّ إنجازه.",n:"نيلسون مانديلا",m:"عن إنجاز العمل الصعب"}},
 {en:{q:"The expert in anything was once a beginner.",n:"Helen Hayes",m:"On starting to learn"},
  fr:{q:"L'expert en toute chose a d'abord été un débutant.",n:"Helen Hayes",m:"Sur le début de l'apprentissage"},
  ar:{q:"الخبير في أي مجال كان في يومٍ ما مبتدئًا.",n:"هيلين هايز",m:"عن بداية التعلّم"}},
 {en:{q:"Success is the sum of small efforts, repeated day after day.",n:"Robert Collier",m:"On daily effort"},
  fr:{q:"Le succès est la somme de petits efforts, répétés jour après jour.",n:"Robert Collier",m:"Sur l'effort quotidien"},
  ar:{q:"النجاح هو مجموع جهود صغيرة تتكرر يومًا بعد يوم.",n:"روبرت كولير",m:"عن الجهد اليومي"}},
 {en:{q:"The beautiful thing about learning is that no one can take it away from you.",n:"B.B. King",m:"On knowledge"},
  fr:{q:"Ce qu'il y a de beau dans l'apprentissage, c'est que personne ne peut vous l'enlever.",n:"B.B. King",m:"Sur le savoir"},
  ar:{q:"أجمل ما في التعلّم أن لا أحد يستطيع أن يأخذه منك.",n:"بي بي كينغ",m:"عن المعرفة"}},
 {en:{q:"A person who never made a mistake never tried anything new.",n:"Albert Einstein",m:"On learning from mistakes"},
  fr:{q:"Celui qui n'a jamais fait d'erreur n'a jamais essayé quelque chose de nouveau.",n:"Albert Einstein",m:"Sur les erreurs et l'apprentissage"},
  ar:{q:"من لم يخطئ قطّ، لم يجرّب شيئًا جديدًا قطّ.",n:"ألبرت أينشتاين",m:"عن التعلّم من الخطأ"}},
 {en:{q:"Don't let what you cannot do interfere with what you can do.",n:"John Wooden",m:"Basketball coach · teacher"},
  fr:{q:"Ne laissez pas ce que vous ne pouvez pas faire gêner ce que vous pouvez faire.",n:"John Wooden",m:"Entraîneur · enseignant"},
  ar:{q:"لا تدع ما لا تستطيع فعله يعيق ما تستطيع فعله.",n:"جون وودن",m:"مدرب · معلّم"}},
 {en:{q:"Motivation gets you started. Habit keeps you going.",n:"Jim Ryun",m:"Olympic runner"},
  fr:{q:"La motivation vous fait démarrer. L'habitude vous fait continuer.",n:"Jim Ryun",m:"Coureur olympique"},
  ar:{q:"التحفيز يبدأ بك. والعادات هي ما يبقيك مستمرًا.",n:"جيم رايون",m:"عداء أولمبي"}},
 {en:{q:"There are no shortcuts to any place worth going.",n:"Beverly Sills",m:"On steady progress"},
  fr:{q:"Il n'y a pas de raccourci vers un endroit qui en vaut la peine.",n:"Beverly Sills",m:"Sur le progrès régulier"},
  ar:{q:"لا توجد طرق مختصرة إلى مكان يستحق الوصول إليه.",n:"بيفرلي سيلز",m:"عن التقدّم الثابت"}},
 {en:{q:"Teachers can open the door, but you must enter by yourself.",n:"Chinese proverb",m:"On personal effort"},
  fr:{q:"Les professeurs peuvent ouvrir la porte, mais c'est à vous d'entrer.",n:"Proverbe chinois",m:"Sur l'effort personnel"},
  ar:{q:"المعلّم يفتح الباب، لكن عليك أنت أن تدخل.",n:"مثل صيني",m:"عن الجهد الشخصي"}},
 {en:{q:"There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",n:"Colin Powell",m:"On hard work"},
  fr:{q:"Il n'y a pas de secret du succès. C'est le fruit de la préparation, du travail et de l'apprentissage après l'échec.",n:"Colin Powell",m:"Sur le travail"},
  ar:{q:"لا أسرار للنجاح. إنه نتيجة الاستعداد والعمل الجاد والتعلّم من الفشل.",n:"كولين باول",m:"عن العمل الجاد"}},
 {en:{q:"An investment in knowledge pays the best interest.",n:"Benjamin Franklin",m:"On the value of study"},
  fr:{q:"Un investissement dans le savoir rapporte les meilleurs intérêts.",n:"Benjamin Franklin",m:"Sur la valeur des études"},
  ar:{q:"الاستثمار في المعرفة يعطي أفضل عائد.",n:"بنجامين فرانكلين",m:"عن قيمة الدراسة"}}
];

/* ---- ROOMS (the 4 salles) ----
   images: placeholder seeds now. For real photos use paths like "images/salle1-1.jpg"
   (any entry containing "/" is used as a direct path — no code change needed). */
const ROOMS_DATA = [
 {num:"01",images:["cs-room1-a","cs-room1-b","cs-room1-c","cs-room1-d"],
  name:{en:"The big room",fr:"La grande salle",ar:"القاعة الكبرى"},
  tag:{en:"Main classes · all levels",fr:"Cours principaux · tous niveaux",ar:"الدروس الرئيسية · كل المستويات"}},
 {num:"02",images:["cs-room2-a","cs-room2-b","cs-room2-c","cs-room2-d"],
  name:{en:"The quiet room",fr:"La salle calme",ar:"القاعة الهادئة"},
  tag:{en:"Small groups · homework help",fr:"Petits groupes · aide aux devoirs",ar:"مجموعات صغيرة · دعم الواجبات"}},
 {num:"03",images:["cs-room3-a","cs-room3-b","cs-room3-c","cs-room3-d"],
  name:{en:"The languages room",fr:"La salle des langues",ar:"قاعة اللغات"},
  tag:{en:"Conversation · FR · EN · AR",fr:"Conversation · FR · EN · AR",ar:"محادثة · فر · إنج · ع"}},
 {num:"04",images:["cs-room4-a","cs-room4-b","cs-room4-c","cs-room4-d"],
  name:{en:"The lycée room",fr:"La salle du lycée",ar:"قاعة التأهيلي"},
  tag:{en:"TC – 2BAC sessions",fr:"Séances TC – 2BAC",ar:"حصص الجذع – 2باك"}}
];

/* ---- TEACHERS (demo names — replace with the real profs) ----
   whatsapp: teacher's own number, digits only — used ONLY if direct:true
   direct:   true = publish teacher's number (consented) · false = route via the centre   */
const TEACHERS = [
 {seed:"souifi-prof-yassine", levels:["college","lycee"], direct:false, whatsapp:"",
  name:{en:"Yassine El Amrani",fr:"Yassine El Amrani",ar:"ياسين العمراني"},
  subject:{en:"Mathematics",fr:"Mathématiques",ar:"الرياضيات"},
  bio:{en:"Fifteen years in a public collège; by evening, makes the formulas finally click.",fr:"Quinze ans dans un collège public ; le soir, il fait enfin cliquer les formules.",ar:"خمسة عشر عامًا في إعدادي عمومي؛ ومساءً يشرح حتى تترسخ الصيغ أخيرًا."},
  badge:{en:"School teacher",fr:"Enseignant titulaire",ar:"أستاذ معتمد"},
  exp:{en:"15 years",fr:"15 ans",ar:"15 سنة"}},
 {seed:"souifi-prof-salma", levels:["lycee"], direct:false, whatsapp:"",
  name:{en:"Salma Benkirane",fr:"Salma Benkirane",ar:"سلمى بنكيران"},
  subject:{en:"Physics-Chemistry",fr:"Physique-Chimie",ar:"الفيزياء والكيمياء"},
  bio:{en:"Her rule: understand first, memorize never.",fr:"Sa règle : comprendre d'abord, mémoriser jamais.",ar:"قاعدتها: افهم أولًا، ولا تحفظ أبدًا."},
  badge:{en:"School teacher",fr:"Enseignante titulaire",ar:"أستاذة معتمدة"},
  exp:{en:"10 years",fr:"10 ans",ar:"10 سنوات"}},
 {seed:"souifi-prof-omar", levels:["college"], direct:false, whatsapp:"",
  name:{en:"Omar Chraibi",fr:"Omar Chraibi",ar:"عمر الشرايبي"},
  subject:{en:"SVT & Sciences",fr:"SVT & Sciences",ar:"علوم الحياة والأرض"},
  bio:{en:"Turns every chapter into a story you can retell at dinner.",fr:"Transforme chaque chapitre en une histoire qu'on peut raconter au dîner.",ar:"يحوّل كل درس إلى حكاية يمكنك إعادتها على العشاء."},
  badge:{en:"School teacher",fr:"Enseignant titulaire",ar:"أستاذ معتمد"},
  exp:{en:"8 years",fr:"8 ans",ar:"8 سنوات"}},
 {seed:"souifi-prof-nadia", levels:["primary","college"], direct:true, whatsapp:"212600000000",
  name:{en:"Nadia Tazi",fr:"Nadia Tazi",ar:"نادية التازي"},
  subject:{en:"Languages · FR · EN · AR",fr:"Langues · FR · EN · AR",ar:"اللغات: الفرنسية · الإنكليزية · العربية"},
  bio:{en:"Conversation first. Grammar quietly comes along.",fr:"La conversation d'abord. La grammaire suit en silence.",ar:"المحادثة أولًا. والقواعد تأتي خلسة."},
  badge:{en:"School teacher",fr:"Enseignante titulaire",ar:"أستاذة معتمدة"},
  exp:{en:"11 years",fr:"11 ans",ar:"11 سنة"}},
 {seed:"souifi-prof-rachid", levels:["primary","college","lycee"], direct:false, whatsapp:"",
  name:{en:"Rachid Bennis",fr:"Rachid Bennis",ar:"رشيد بنيس"},
  subject:{en:"Arabic & Study Methods",fr:"Arabe & Méthodologie",ar:"العربية ومناهج المذاكرة"},
  bio:{en:"Teaches how to learn, not just what to learn.",fr:"Enseigne comment apprendre, pas seulement quoi apprendre.",ar:"يعلّم كيف تتذاكر، لا ماذا تذاكر فقط."},
  badge:{en:"Former school director",fr:"Ex-directeur d'école",ar:"مدير مدرسة سابق"},
  exp:{en:"22 years",fr:"22 ans",ar:"22 سنة"}}
];
const pic = seed => `https://picsum.photos/seed/${seed}/640/420.jpg`;
